image: sonamsamdupkhangsar/springboot-docker:latest

stages:
  - build
  - test

build:
  stage: build
  script:
    - ./gradlew assemble
  only:
    - master

test:
  stage: test
  script:
    - ./gradlew clean test