image: tomohito/springboot-bestpractice:1.0.0

stages:
  - build
  - test

build:
  stage: build
  script:
    - ./gradlew assemble
  only:
    - master

test:
  stage: test
  script:
    - ./gradlew clean test