image: springci/spring-boot-jdk14-ci-image:2.4.x

stages:
  - build
  - test

build:
  stage: build
  script:
    - ./gradlew assemble
  only:
    - master

test:
  stage: test
  script:
    - ./gradlew clean test