image: coderunner/java15:2021-02-09_11-46

stages:
  - build
  - test

build:
  stage: build
  script:
    - ./gradlew assemble
  only:
    - master

test:
  stage: test
  script:
    - ./gradlew clean test