test-runner:
  script:
    - echo "Start CI/CD"

#stages:
#  - build
#  - test
#
#build:
#  stage: build
#  script:
#    - ./gradlew assemble
#  only:
#    - master
#
#test:
#  stage: test
#  script:
#    - ./gradlew clean test